# Generated by the protocol buffer compiler (protoc-perl) DO NOT EDIT!
# source: /home/bernhard/go/pkg/mod/github.com/ipfs/go-unixfs@v0.0.5/pb/unixfs.proto



use strict;
use warnings;

use Google::ProtocolBuffers;
{
    unless (Unixfs::Pb::Data::DataType->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_enum(
            'Unixfs::Pb::Data::DataType',
            [
               ['Raw', 0],
               ['Directory', 1],
               ['File', 2],
               ['Metadata', 3],
               ['Symlink', 4],
               ['HAMTShard', 5],

            ]
        );
    }
    
    unless (Unixfs::Pb::Data->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'Unixfs::Pb::Data',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'Unixfs::Pb::Data::DataType', 
                    'Type', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_BYTES(), 
                    'Data', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_UINT64(), 
                    'filesize', 3, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(), 
                    Google::ProtocolBuffers::Constants::TYPE_UINT64(), 
                    'blocksizes', 4, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_UINT64(), 
                    'hashType', 5, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_UINT64(), 
                    'fanout', 6, undef
                ],

            ],
            undef,

            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (Unixfs::Pb::Metadata->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'Unixfs::Pb::Metadata',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'MimeType', 1, undef
                ],

            ],
            undef,

            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

}
1;
